config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :products do
    get :who_bought, on: :member
    resources :reviews
  end
  resources :support_requests, only: %i[index update]
  scope '(:locale)', defaults: { locale: 'en' } do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  skip_before_action :authorize, only: %i[create update destroy]
  before_action :set_review, only: %i[show edit update destroy]
  before_action :set_product

  # GET /reviews or /reviews.json
  def index
    @reviews = @product.reviews
  end

  # GET /reviews/1 or /reviews/1.json
  def show; end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.product_id = @product.id

    create_respond_to
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @product, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to product_reviews_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def create_respond_to
    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, min: 1, max: 5 %>
  </div>
  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, rows: 10, cols: 60 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', product_reviews_path  %>

app/views/reviews/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>
<h1>Reviews</h1>

<table>
  <thead>
  <tr>
    <th>Rating</th>
    <th>Comment</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.rating %></td>
      <td><%= review.comment %></td>
      <td><%= link_to 'Show', product_review_path(review.product, review) %></td>
      <td><%= link_to 'Edit', edit_product_review_path(review.product, review) %></td>
      <td><%= link_to 'Destroy', product_review_path(review.product, review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', product_path(@product) %> |
<%= link_to 'New Review', new_product_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', product_path(@product) %>

app/views/reviews/show.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>
<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>
<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_product_review_path(@review.product, @review) %> |
<%= link_to 'Back', product_reviews_path(@review.product, @review) %>